export const people = [
  {
    name: "John",
    city: "London",
    jobRole: "Teacher",
    cityUrl: "https://en.wikipedia.org/wiki/London",
    userId: "john123",
  },
  {
    name: "Emily",
    city: "Paris",
    jobRole: "Engineer",
    cityUrl: "https://en.wikipedia.org/wiki/Paris",
    userId: "emily456",
  },
  {
    name: "Robert",
    city: "Berlin",
    jobRole: "Doctor",
    cityUrl: "https://en.wikipedia.org/wiki/Berlin",
    userId: "robert789",
  },
  {
    name: "Sarah",
    city: "New York",
    jobRole: "Chef",
    cityUrl: "https://en.wikipedia.org/wiki/New_York_City",
    userId: "sarah234",
  },
  {
    name: "Daniel",
    city: "Rome",
    jobRole: "Writer",
    cityUrl: "https://en.wikipedia.org/wiki/Rome",
    userId: "daniel567",
  },
  {
    name: "Michael",
    city: "Dubai",
    jobRole: "Designer",
    cityUrl: "https://en.wikipedia.org/wiki/Dubai",
    userId: "michael890",
  },
  {
    name: "Sophia",
    city: "Moscow",
    jobRole: "Nurse",
    cityUrl: "https://en.wikipedia.org/wiki/Moscow",
    userId: "sophia123",
  },
  {
    name: "David",
    city: "Tokyo",
    jobRole: "Developer",
    cityUrl: "https://en.wikipedia.org/wiki/Tokyo",
    userId: "david456",
  },
  {
    name: "Jane",
    city: "Sydney",
    jobRole: "Artist",
    cityUrl: "https://en.wikipedia.org/wiki/Sydney",
    userId: "jane789",
  },
  {
    name: "Olivia",
    city: "Toronto",
    jobRole: "Lawyer",
    cityUrl: "https://en.wikipedia.org/wiki/Toronto",
    userId: "olivia234",
  },
];
